---
- hosts: servera.lab.example.com
  remote_user: root
  become: true
  tasks:
    - name: to check the local time
      command: date
      register: command_result
      changed_when: true
    - name: to print the time
      debug:
        var: command_result.stdout
